name: Build and Test

on:
  push

jobs:
  setup-dependencies:
    name: "Build & Test"
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: true
      - uses: .github/actions/setup_deps
      - run: make
